version: "3.7"

services:
  db:
    command: postgres
    container_name: consumer-db
    image: postgres:14-alpine
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=consumer
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password