package me.teenageorge

object Versions {
    const val postgresTestContainersImageName = "postgres:14-alpine"
    const val jvmTarget = "11"
    const val kotlinXHtmlJvm = "0.8.0"
    const val kotest = "1.0.1"
    const val assertJCore = "3.23.1"
    const val konformJvm = "0.4.0"
    const val mockk = "1.12.4"
    const val junitJupiterEngine = "5.8.2"
    const val bcprovJdk15 = "1.70"
    const val junitJupiter = "5.9.0"
    const val springBootOpenApiWebfluxUi = "1.6.11"
    const val springMockk = "3.1.1"
    const val springBootCloudStarterBootstrap = "3.1.3"
    const val jooq = "3.16.6"
    const val kotlin = "1.6.21"
    const val springBoot = "2.6.8"
    const val testContainers = "1.17.5"
    const val postgres = "42.3.6"
    const val jakartaXml = "3.0.1"
    const val kotlinLogging = "2.1.23"
    const val embeddedPostgresql = "2.2.0"
}